version: '3.1'
services:
  mysql:
    image: mysql:5.7.22
    container_name: desafioMovaSql
    environment:
      - MYSQL_DATABASE=endereco
      - MYSQL_USER=rafael
      - MYSQL_PASSWORD=Rafinha@123
      - MYSQL_ROOT_PASSWORD=Rafinha@123
      - TZ=America/Sao_Paulo
    ports:
      - "3306:3306"

  php:
    image: php:8.0-apache
    container_name: desafioMovaPhp
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
    links:
      - mysql
